### ISSUE TITLE
Current Work in Progress

### ISSUE THREAD

**Issue by youngcet** [youngcet/task_scheduler#1]
- [x] Add a line to indicate the current time.
- [x] Implemented transparency for past events when dragged.
- [x] Fix confusion when setting intervals of 30 minutes and selecting 5 minutes.
- [x] Introduced a start and end time popup during dragging.
- [x] Update left-hand clock section to show only main hours when intervals of 5 minutes or smaller are set.
- [x] Fix widget resize issue
- [x] #3

**Comment by youngcet** [comment]
**Fix confusion when setting intervals of 30 minutes and selecting 5 minutes.**
 - The widget only supports 10, 15, 20, 30 and 60 minute intervals. An exception is thrown when the interval set is not one of the supported intervals.
 
**Update left-hand clock section to show only main hours when intervals of 5 minutes or smaller are set.**
- Introduced a new property `showHoursOnly` in `SchedulerTimeSettings` to only show hours.
```
timeFormat: SchedulerTimeSettings(
      minuteInterval: timeInterval,
      use24HourFormat: true,
      includePeriod: true,
      includeMinutes: false,
      showHoursOnly: true // defaults to false
    ),
```

**Comment by Ec4n** [comment]
I feel it is my duty to thank the wonderful people who contributed to this project.

**Comment by youngcet** [comment]
@Ec4n you can have a look at the updates in dev branch https://github.com/youngcet/task_scheduler/tree/dev

**Comment by youngcet** [comment]
version 0.0.3 released addressing these enhancements.
