### ISSUE TITLE
Adding entries around midnight

### ISSUE THREAD

**Issue by Insolita-code** [youngcet/task_scheduler#9]
https://github.com/youngcet/task_scheduler/blob/baf90f4f30d31f9054e6187bb29559b63b1d9455/lib/src/task_scheduler.dart#L241

There appears to be a restriction on the scheduleStartTime and scheduleEndTimes that restrict adding entries between the times of 23:00 - 01:00. Specifically the restriction prevents creating events from 23:00 to midnight and from midnight to 01:00.

A use case I had in mind would require the ability to add entries on the full 24 hour period of a day. To clarify, I do not mean needing an entry to be allowed to span multiple days.

Thank you for providing an interesting component

**Comment by youngcet** [comment]
I can remove the restrictions for this use case "**Specifically the restriction prevents creating events from 23:00 to midnight and from midnight to 01:00**" to allow entries to be added on a full 24 hour period of a day (between 00:00 and 00:00).

**Comment by youngcet** [comment]
A full 24 hour day added to v0.0.3+2

```
...
scheduleStartTime: ScheduleTimeline(hour: 0), // 0 start at midnight
scheduleEndTime: ScheduleTimeline(hour: 24), // 24 end at midnight
...
```
